version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: laravel-app
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-net

  backend-nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    ports:
      - "8000:80"
    networks:
      - app-net

  frontend:
    image: node:20
    container_name: react-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
    - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
